# Generated by Django 4.2.6 on 2023-11-14 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(default='valor_test', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('contrasena', models.CharField(default='valor_test', max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(default='valor_test', max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_servicio', models.CharField(choices=[('tv', 'TV'), ('internet', 'Internet'), ('telefonia', 'Telefonía')], max_length=10)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_internet', models.CharField(blank=True, max_length=50)),
                ('tipo_canal_tv', models.CharField(blank=True, max_length=50)),
                ('tipo_telefonia', models.CharField(blank=True, max_length=50)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.administrador')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
