# Generated by Django 4.2.4 on 2023-11-16 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('detalles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_iniciacion', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('comuna', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('contrasena', models.CharField(default='123', max_length=50)),
                ('rol_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rol')),
            ],
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='administrador',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plan'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.suscripcion'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
