# Generated by Django 4.2.4 on 2023-11-17 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_boleta_rol_suscripcion_usuario_delete_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('velocidad', models.IntegerField()),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_contrato', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Telefonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('gigas', models.IntegerField()),
                ('minutos', models.IntegerField()),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_telefonia', models.CharField(blank=True, max_length=50)),
                ('tiempo_contrato', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Television',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canales_SD', models.IntegerField()),
                ('canales_HD', models.IntegerField()),
                ('canales_adicionales', models.CharField(max_length=255, null=True)),
                ('tiempo_contrato', models.IntegerField()),
                ('tipo_television', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='plan',
        ),
        migrations.AddField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='valor_con_descuento',
            field=models.DecimalField(decimal_places=2, default=999999, max_digits=10),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='detalles',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.rol'),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.AddField(
            model_name='boleta',
            name='descuento',
            field=models.ForeignKey(default=9999999, on_delete=django.db.models.deletion.CASCADE, to='app.descuento'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='plan_internet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plan_internet'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='plan_telefonia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plan_telefonia'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='plan_television',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plan_television'),
        ),
    ]
