# Generated by Django 4.2.4 on 2023-11-17 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usuario_rol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(default=9999999, on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='descuento',
            field=models.ForeignKey(default=9999999, on_delete=django.db.models.deletion.CASCADE, to='app.descuento'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='valor_con_descuento',
            field=models.DecimalField(decimal_places=2, default=9999999, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_id',
            field=models.ForeignKey(blank=True, default=9999999, on_delete=django.db.models.deletion.CASCADE, to='app.rol'),
        ),
    ]
