# Generated by Django 4.2.4 on 2023-11-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_rol_id_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_internet',
            name='descripcion',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='plan_telefonia',
            name='descripcion',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='plan_television',
            name='descripcion',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
