# Generated by Django 4.2.6 on 2023-11-27 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_plan_internet_descripcion_plan_telefonia_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha_Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('cliente', models.ForeignKey(default=9999999, on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
