# Generated by Django 4.2.6 on 2023-12-02 06:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plan_internet')),
                ('telefonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plan_telefonia')),
                ('television', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plan_television')),
            ],
        ),
        migrations.RemoveField(
            model_name='fecha_inicio',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Tipo_Servicio',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Fecha_Inicio',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='tipo_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipo_plan'),
        ),
    ]
