# Generated by Django 4.2.6 on 2023-12-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tipo_plan_remove_fecha_inicio_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan_internet',
            old_name='precio_mensual',
            new_name='valor_mensual',
        ),
        migrations.RenameField(
            model_name='plan_telefonia',
            old_name='precio_mensual',
            new_name='valor_mensual',
        ),
        migrations.RenameField(
            model_name='plan_television',
            old_name='precio_mensual',
            new_name='valor_mensual',
        ),
        migrations.RemoveField(
            model_name='plan_internet',
            name='tiempo_contrato',
        ),
        migrations.RemoveField(
            model_name='plan_internet',
            name='velocidad',
        ),
        migrations.RemoveField(
            model_name='plan_telefonia',
            name='gigas',
        ),
        migrations.RemoveField(
            model_name='plan_telefonia',
            name='minutos',
        ),
        migrations.RemoveField(
            model_name='plan_telefonia',
            name='tiempo_contrato',
        ),
        migrations.RemoveField(
            model_name='plan_telefonia',
            name='tipo_telefonia',
        ),
        migrations.RemoveField(
            model_name='plan_television',
            name='canales_HD',
        ),
        migrations.RemoveField(
            model_name='plan_television',
            name='canales_SD',
        ),
        migrations.RemoveField(
            model_name='plan_television',
            name='canales_adicionales',
        ),
        migrations.RemoveField(
            model_name='plan_television',
            name='tiempo_contrato',
        ),
        migrations.RemoveField(
            model_name='plan_television',
            name='tipo_television',
        ),
        migrations.AddField(
            model_name='plan_internet',
            name='adicional',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='plan_internet',
            name='extensor',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='plan_internet',
            name='instalacion',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='plan_telefonia',
            name='adicional',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='plan_telefonia',
            name='extras',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='plan_telefonia',
            name='roaming',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='plan_television',
            name='Asistencia',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='plan_television',
            name='adicional',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='plan_television',
            name='extras',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan_telefonia',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
