# Generated by Django 4.2.6 on 2023-12-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_precio_mensual_plan_internet_valor_mensual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_internet',
            name='valor_mensual',
            field=models.CharField(default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan_telefonia',
            name='valor_mensual',
            field=models.CharField(default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan_television',
            name='valor_mensual',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
