# Generated by Django 4.2.6 on 2023-12-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_plan_internet_valor_mensual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecha_emision',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha_vencimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_iniciacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateTimeField(),
        ),
    ]
